services:
  api:
    image: ${DOCKER_REGISTRY-}api
    build:
      context: .
      dockerfile: API/Dockerfile
    depends_on:
      database:
        condition: service_healthy
    environment:
      ASPNETCORE_ENVIRONMENT: "Docker"
      ASPNETCORE_URLS: "https://+:5001;http://+:5000"
      ASPNETCORE_Kestrel__Certificates__Default__Path: /https/aspnetapp.pfx
      ASPNETCORE_Kestrel__Certificates__Default__Password: "password123"
      DB_PASSWORD: "${DB_PASSWORD}"
    volumes:
      - ~/.aspnet/https:/https:ro
    ports:
      - "5000:5000"
      - "5001:5001"

  database:
    image: postgres:latest
    container_name: database
    environment:
      POSTGRES_DB: seepaw
      POSTGRES_USER: seepaw
      POSTGRES_PASSWORD: seepawpwd
    volumes:
      - pg_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U seepaw -d seepaw"]
      interval: 5s
      timeout: 3s
      retries: 10

volumes:
  pg_data:
