using System.Text.Json;
using Microsoft.AspNetCore.Http;
using WebAPI.Middleware;

namespace Tests.Middleware;

/// <summary>
/// Middleware responsible for intercepting HTTP 401 (Unauthorized) responses 
/// generated by ASP.NET Identity or authentication mechanisms, and replacing 
/// them with a standardized JSON structure. 
/// 
/// This ensures that API clients always receive consistent error responses 
/// for unauthorized access attempts, improving clarity and usability.
/// </summary>
public class IdentityResponseMiddlewareTest
{
    private readonly DefaultHttpContext _context;
    private readonly RequestDelegate _next;
    private readonly IdentityResponseMiddleware _middleware;

    /// <summary>
    /// Initializes a new instance of the <see cref="IdentityResponseMiddleware"/> class.
    /// </summary>
    /// <param name="next">
    /// The next middleware in the request pipeline. 
    /// Used to invoke subsequent components after this middleware executes.
    /// </param>
    public IdentityResponseMiddlewareTest()
    {
        _context = new DefaultHttpContext();
        _context.Response.Body = new MemoryStream(); 
        _next = async ctx =>
        {
            // simula a escrita de uma resposta 401 com um corpo JSON específico
            ctx.Response.StatusCode = StatusCodes.Status401Unauthorized;
            var responseBody = ctx.Items["SimulatedBody"] as string ?? string.Empty;
            await ctx.Response.WriteAsync(responseBody);
        };
        _middleware = new IdentityResponseMiddleware(_next);
    }

    /// <summary>
    /// Intercepts the HTTP context pipeline to check for 401 responses.
    /// When an unauthorized response is detected, replaces its body with 
    /// a custom JSON message providing more meaningful details about the cause.
    /// </summary>
    /// <param name="context">The current HTTP request and response context.</param>
    [Theory]
    [InlineData("InvalidLoginAttempt", "Invalid credentials. Please check your email or password.", null)]
    [InlineData("LockedOut", "Account temporarily blocked: maximum login attempts reached.", "LockedOut")]
    [InlineData("NotAllowed", "Account not confirmed. Please verify your email.", "NotAllowed")]
    [InlineData("OtherText", "Authentication required. Please provide valid credentials.", "Unauthorized")]
    public async Task InvokeAsync_ReturnsExpectedCustomJson(string inputBody, string expectedMessage, string? expectedDetails)
    {
        // Arrange
        _context.Items["SimulatedBody"] = inputBody;

        // Act
        await _middleware.InvokeAsync(_context);

        // Assert
        _context.Response.Body.Seek(0, SeekOrigin.Begin);
        var reader = new StreamReader(_context.Response.Body);
        var body = await reader.ReadToEndAsync();

        using var doc = JsonDocument.Parse(body);
        var root = doc.RootElement;

        Assert.Equal(401, root.GetProperty("status").GetInt32());
        Assert.Equal(expectedMessage, root.GetProperty("message").GetString());

        var detailsProp = root.GetProperty("details").GetString();
        Assert.Equal(expectedDetails, detailsProp);
    }
}