name: Deploy to Azure

on:
  workflow_run:
    workflows: ["Semantic Release"]
    types:
      - completed
    branches: [main]
  workflow_dispatch:

env:
  REGISTRY_LOGIN_SERVER: ${{ secrets.REGISTRY_LOGIN_SERVER }}
  IMAGE_NAME: api
  
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: Production
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with: 
        fetch-depth: 0
      
    - name: Get latest version
      id: version
      run: |
        # Obter a última tag criada
        VERSION=$(git describe --tags --abbrev=0)
        echo "version=$VERSION" >> $GITHUB_OUTPUT
        echo "Deployment Version: $VERSION"
      
    - name: Log in to Azure Container Registry
      uses: docker/login-action@v3
      with:
        registry: ${{ secrets.REGISTRY_LOGIN_SERVER }}
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}
        
    - name: Build and push Docker image
      run: |
        VERSION=${{ steps.version.outputs.version }}
        
        # Build
        docker build -f WebAPI/Dockerfile \
          -t ${{ env.REGISTRY_LOGIN_SERVER }}/${{ env.IMAGE_NAME }}:$VERSION \
          -t ${{ env.REGISTRY_LOGIN_SERVER }}/${{ env.IMAGE_NAME }}:latest \
          .
          
        # Push com versão específica
        docker push ${{ env.REGISTRY_LOGIN_SERVER }}/${{ env.IMAGE_NAME }}:$VERSION
        
        # Push também como latest
        docker push ${{ env.REGISTRY_LOGIN_SERVER }}/${{ env.IMAGE_NAME }}:latest
        
        echo "Images pushed to Azure:"
        echo "  - ${{ env.REGISTRY_LOGIN_SERVER }}/${{ env.IMAGE_NAME }}:$VERSION"
        echo "  - ${{ env.REGISTRY_LOGIN_SERVER }}/${{ env.IMAGE_NAME }}:latest"
        
    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'seepaw-api'
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        images: '${{ env.REGISTRY_LOGIN_SERVER }}/${{ env.IMAGE_NAME }}:${{ steps.version.outputs.version }}'